apiVersion: v1
kind: Service
metadata:
  name: coder-cache
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    app: coder-cache
  type: NodePort
  ports:
    - name: tcp-redis
      protocol: "TCP"
      port: 6379
      #targetPort: 32379
      nodePort: 32379
