{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ .Release.Name }}
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape
  # By default, Prometheus discovers PodMonitors and ServiceMonitors within its namespace,
  # that are labeled with the same release tag as the prometheus-operator release
  namespace: monitoring
  labels:
    app: {{ .Release.Name }}
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape
    # By default, Prometheus discovers PodMonitors and ServiceMonitors within its namespace,
    # that are labeled with the same release tag as the prometheus-operator release
    release: prom-stack

spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}

  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  endpoints:
    - path: {{ .Values.monitoring.endpoints.svc_monitor }}
      port: http
      interval: 15s
  {{- end }}
