container:
  image: core.harbor.domain/vranasm/coder
  image_tag: latest
  command:
    - "java"
  args:
    - "-Dcom.sun.management.jmxremote"
    - "-jar"
    - "coder.jar"
replicas: 3
ports:
  container: 8080
  service: 8080
ingress:
  domain: coder.vranasm.domain
  hidden_path: "/endpoints/(.*)"
resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 4096Mi
monitoring:
  readiness:
    initialDelaySeconds: 15
  liveness:
    initialDelaySeconds: 15
  endpoints:
    healthcheck: /actuator/health
    #svc_monitor: /actuator/prometheus
    health: /actuator/health
    #env: /actuator/env
    #metrics: /actuator/metrics
    # jiri.moc - testing pipeline
liquibase:
coder:
  DB_URL:  jdbc:sqlserver://mssql01.ais-servis.cz:1433;databaseName=codertest;encrypt=true;trustServerCertificate=true
  DB_USER: disp
  REDIS_HOST: coder-cache.coder-app.svc.cluster.local
  REDIS_PORT: '6379'
